# Generated by Django 3.2.9 on 2022-04-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('N', 'Normal'), ('U', 'Urgente'), ('I', 'Importante'), ('P', 'Prioritario')], default='N', max_length=1)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
